# Generated by Django 4.2.30 on 2026-07-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequestapprovalmutation',
            name='access_request_approval',
        ),
        migrations.RemoveField(
            model_name='accessrequestapprovalmutation',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='historicalaccessrequestapproval',
            name='access_request',
        ),
        migrations.RemoveField(
            model_name='historicalaccessrequestapproval',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='historicalaccessrequestapproval',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaccessrequestapproval',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='historicalaccessrequestapproval',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='AccessRequestApproval',
        ),
        migrations.DeleteModel(
            name='AccessRequestApprovalMutation',
        ),
        migrations.DeleteModel(
            name='HistoricalAccessRequestApproval',
        ),
    ]
