# Generated by Django 4.2.30 on 2026-07-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('access_request', '0002_remove_accessrequestapprovalmutation_access_request_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='administrative_level',
            field=models.CharField(blank=True, choices=[('PAA', 'PAA'), ('VILLAGE', 'Village')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='section_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_requests', to='auth.group'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_category',
            field=models.CharField(blank=True, choices=[('TASAF_STAFF', 'TASAF Staff'), ('PAA_STAFF', 'PAA Staff'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrequest',
            name='administrative_level',
            field=models.CharField(blank=True, choices=[('PAA', 'PAA'), ('VILLAGE', 'Village')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrequest',
            name='section_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='historicalaccessrequest',
            name='user_category',
            field=models.CharField(blank=True, choices=[('TASAF_STAFF', 'TASAF Staff'), ('PAA_STAFF', 'PAA Staff'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
