# Generated by Django 4.2.30 on 2026-08-14 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('access_request', '0003_accessrequest_administrative_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_sponsor', to='auth.group')),
                ('sponsor_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.role')),
            ],
        ),
    ]
